# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoann Pigné - Lectures
email: yoann.pigne@univ-lehavre.fr
description: > # this means to ignore newlines until "baseurl:"
  Web pages realted to my lectures and labs at the University of La Havre, France.
baseurl: "/teaching" # the subpath of your site, e.g. /blog
url: "http://pigne.org" # the base hostname & protocol for your site
twitter_username: yopgn
github_username:  pigne

future: true

permalink: /:categories/:title.html
permalink: /:categories/:title


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true



# The Reveal theme
reveal_theme: simple.css
# The Reveal transition
reveal_transition: linear
reveal_transition_speed: fast


# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: /bower_components/reveal.js/css/theme/
# Embed Server-side speaker notes?
reveal_notes_server: false
# Additional reveal.js options
reveal_options:
reveal_controls: false
reveal_center: true
reveal_progress: true
reveal_history: false
reveal_slide_number: true

# Additional reveal.js dependencies
reveal_dependencies:
# Reveal.js subdirectory
reveal_path: /bower_components/reveal.js/
