title: Teaching
author:
  name: Yoann Pigné
  email: yoann.pigne@univ-lehavre.fr
description: > # this means to ignore newlines until "baseurl:"
  Web pages related to my lectures and labs at the University Le Havre Normandy, France.
tagline: "lectures and labs @ University Le Havre Normandy"
baseurl: "/teaching" # the subpath of your site, e.g. /blog
url: "http://pigne.org" # the base hostname & protocol for your site
github_username:  pigne
twitter:
  username: yopgn
  card: summary
logo: /assets/yp.svg

future: true

permalink: /:categories/:title.html
permalink: /:categories/:title

remote_theme: chesterhow/tale

plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap




# Build settings
markdown: kramdown


kramdown:
  input: GFM
  parse_block_html: true


collections:
  matieres:
    label: matieres
    permalink: /:path/
    output: true



